name: Continuous Deployment to Fly.io
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Backend to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust this to your project's Node.js version
      - name: Install and Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Copy Frontend Build to Backend
        run: cp -r frontend/build/* backend/dist/ # Adjust this path based on your project's structure
      - name: Install Backend Dependencies and Build
        run: |
          cd backend
          npm install
          npm run build
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 'latest' # Ensures you use the latest version of Flyctl
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: ./backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
